# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

paginate: 5
# pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
#   enabled: true

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 10

# https://github.com/jekyll/minima/blob/master/_config.yml
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: theredpea
    github:  theredpea
    facebook: nathaniel.m.anderson
    linkedin: nathaniel-anderson-72702a14

show_excerpts: true
version: 0.0.1
title: bitmask
tagline: Nate Anderson's site
email: nate.muir.anderson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nate Anderson's site
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theredpea
github_username:  theredpea

# Build settings
theme: jekyll-theme-hyde
# https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll
# Doesnt produce public/css -- publish/css folder into ---> assets/css
# remote_theme: poole/hyde
# emp/jekyll-remote-theme-20191209-17492-1h12gk2.zip
#       Remote Theme: Unzipping C:/Users/there/AppData/Local/Temp/jekyll-remote-theme-20191209-17492-1h12gk2.zip to C:/Users/there/AppData/Local/Temp/jekyll-remote-theme-20191209-17492-8tdfvc
#          Requiring: github-pages
#   Dependency Error: Yikes! It looks like you don't have github-pages or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- github-pages' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
# jekyll 3.8.6 | Error:  github-pages

# NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
# Faraday::Error::ClientError.inherited called from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
#   Dependency Error: Yikes! It looks like you don't have jekyll-include-cache or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-include-cache' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

# remote_theme: benbalter/retlab
plugins:
  # - jekyll-feed
  # - jekyll-paginate-v2
  - jekyll-paginate
  - jekyll-remote-theme
  # For retlab theme:
  
  # - jekyll-include-cache
  # - jekyll-seo-tag
  # - jekyll-avatar
  # - jekyll-github-metadata
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
