# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

collections:
  - featured_works
  
paginate: 5 
# https://stackoverflow.com/a/27016002/1175496
# > To have pagination work in another page other than your index.html, 
# > create a new folder for that page (say, poems/) and change what would have been "poems.html" to "poems/index.html". 
# > After that, your "paginate_path" in _config.yml should be 'paginate_path: "poems/page:num/"'.
# https://jekyllrb.com/docs/pagination/
# > Pagination does not work from within Markdown files from your Jekyll site. 
# > Pagination works when called from within the HTML file, named index.html, which optionally may reside in and produce pagination from within a subdirectory, 
# > via the paginate_path configuration value.

 
#Notice both leading and trailing slash
# paginate_path: "posts/page:num"
# paginate_path: "posts/page:num/"
paginate_path: "/posts/page:num/"
# pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
#   enabled: true

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 10

# https://github.com/jekyll/minima/blob/master/_config.yml
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: theredpea
    github:  theredpea
    facebook: nathaniel.m.anderson
    linkedin: nathaniel-anderson-72702a14
    # stackoverflow: 1175496/the-red-pea
    stackoverflow: '1175496'

show_excerpts: true
version: 0.0.1
title: bitmask
subtitle: studios
tagline: Nate Anderson's site
email: nate.muir.anderson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nate Anderson's site
# https://github.com/github/pages-gem/issues/460
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theredpea
github_username:  theredpea

#CNAME record
# https://support.google.com/domains/answer/9211383?hl=en
#Subdomain forwarding
# https://support.google.com/domains/answer/6072198

# https://github.com/jekyll/jekyll/issues/4705#issuecomment-200991736
repository: theredpea/theredpea.github.io

#      Jekyll Feed: Generating feed for posts
# Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/post.html
#            ERROR: YOUR SITE COULD NOT BE BUILT:
#                   ------------------------------------
#                   No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
# https://github.com/mmistakes/minimal-mistakes/issues/1992#issuecomment-453699142
# github: 
#   repository_url: 'https://github.com/theredpea/theredpea.github.io'
# Build settings
# theme: jekyll-theme-hyde
# https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll
# Doesnt produce public/css -- publish/css folder into ---> assets/css
# remote_theme: poole/hyde
remote_theme: theredpea/hyde
# emp/jekyll-remote-theme-20191209-17492-1h12gk2.zip
#       Remote Theme: Unzipping C:/Users/there/AppData/Local/Temp/jekyll-remote-theme-20191209-17492-1h12gk2.zip to C:/Users/there/AppData/Local/Temp/jekyll-remote-theme-20191209-17492-8tdfvc
#          Requiring: github-pages
#   Dependency Error: Yikes! It looks like you don't have github-pages or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- github-pages' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
# jekyll 3.8.6 | Error:  github-pages

# NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
# Faraday::Error::ClientError.inherited called from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
#   Dependency Error: Yikes! It looks like you don't have jekyll-include-cache or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-include-cache' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

# remote_theme: benbalter/retlab
plugins:
  # - jekyll-feed
  # - jekyll-paginate-v2
  - jekyll-paginate
  - jekyll-remote-theme
  # For retlab theme:
  
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-avatar
  #  GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  - jekyll-github-metadata
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
